version: '3'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_server
      MYSQL_USER: chat_server
      MYSQL_PASSWORD: chat_server
    networks:
      - BackEnd

  backend:
    depends_on:
      - database
    build:
      context: .
      args:
        app_env: ${APP_ENV}
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/go/src/github.com/sail3/chat_server
    networks:
      - FrontEnd
      - BackEnd
networks:
  FrontEnd:
    driver: bridge
  BackEnd:
    driver: bridge
